# Generated by Django 5.2.3 on 2025-07-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, help_text='Upload a video file', null=True, upload_to='video/homepage_videos')),
                ('video_link', models.URLField(blank=True, help_text='Video Link', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(choices=[('hero', 'Hero'), ('middle', 'Middle')], help_text='Video Position', max_length=20, unique=True)),
            ],
        ),
    ]
