# Generated by Django 5.2.3 on 2025-07-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagevideo',
            options={'verbose_name': 'Homepage', 'verbose_name_plural': 'Homepage'},
        ),
    ]
