# Generated by Django 5.2.3 on 2025-07-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_homepagevideo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagevideo',
            options={'verbose_name': 'Homepage Video', 'verbose_name_plural': 'Homepage Videos'},
        ),
    ]
