# Generated by Django 5.2.3 on 2025-07-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, help_text='Upload an image file', null=True, upload_to='images/legaldocs')),
                ('image_link', models.URLField(blank=True, help_text='Image Link', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
            ],
            options={
                'verbose_name': 'Legal Dococument',
                'verbose_name_plural': 'Legal Documents',
            },
        ),
    ]
