# Generated by Django 5.2.3 on 2025-07-19 09:38

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('destination', '0001_initial'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number', max_length=128, region=None)),
                ('country', django_countries.fields.CountryField(help_text='Country', max_length=2)),
                ('airlines', models.CharField(choices=[('Yeti Airlines', 'Yeti Airlines'), ('Fly Emirates', 'Fly Emirates'), ('Qatar Airways', 'Qatar Airways'), ('Delta Airlines', 'Delta Airlines'), ('Lufthansa', 'Lufthansa'), ('Air France', 'Air France'), ('British Airways', 'British Airways'), ('Southwest Airlines', 'Southwest Airlines'), ('ANA', 'ANA'), ('Japan Airlines', 'Japan Airlines')], help_text='Airlines', max_length=100)),
                ('no_of_travellers', models.IntegerField(help_text='Number of travellers')),
                ('arrival_date', models.DateField(help_text='Arrival Date')),
                ('departure_date', models.DateField(help_text='Departure Date')),
                ('service_type', models.CharField(choices=[('budget', 'Budget'), ('standard', 'Standard'), ('premium', 'Premium')], help_text='Service Type', max_length=10)),
                ('customize_trip', models.TextField(blank=True, help_text='Customize Trip Here', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('activity', models.ForeignKey(help_text='Activity', on_delete=django.db.models.deletion.PROTECT, to='activities.activity')),
                ('destination', models.ForeignKey(help_text='Destination', on_delete=django.db.models.deletion.PROTECT, to='destination.destination')),
                ('package', models.ForeignKey(help_text='Package', on_delete=django.db.models.deletion.PROTECT, to='package.package')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
