# Generated by Django 5.2.3 on 2025-07-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ManyToManyField(help_text='Package', to='package.package'),
        ),
    ]
