# Generated by Django 5.2.3 on 2025-07-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog Title', max_length=100)),
                ('reading_time', models.CharField(help_text='Reading Time', max_length=20)),
                ('description', models.TextField(help_text='Blog Description', max_length=1000)),
                ('image_file', models.ImageField(blank=True, help_text='Upload an image file', null=True, upload_to='images/blogs')),
                ('popular', models.BooleanField(default=False, help_text='Mark as popular?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Published at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
