# Generated by Django 5.2.3 on 2025-07-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='show',
            field=models.BooleanField(default=False, help_text='Show?'),
        ),
    ]
