# Generated by Django 5.2.3 on 2025-07-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Popup Title', max_length=100)),
                ('image_file', models.ImageField(blank=True, help_text='Upload an image file', null=True, upload_to='images/popup')),
                ('image_link', models.URLField(blank=True, help_text='Image Link', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
