# Generated by Django 5.2.3 on 2025-07-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popup',
            options={'verbose_name': 'Pop Up', 'verbose_name_plural': 'Pop Ups'},
        ),
    ]
