# Generated by Django 5.2.3 on 2025-07-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file', null=True, upload_to='images/team'),
        ),
    ]
