# Generated by Django 5.2.3 on 2025-07-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('destination', '0002_destination_accomodation_destination_best_season_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='destination',
        ),
        migrations.AddField(
            model_name='activity',
            name='destination',
            field=models.ManyToManyField(help_text='Destination', to='destination.destination'),
        ),
    ]
