# Generated by Django 5.2.3 on 2025-07-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_activity_destination_activity_destination'),
        ('destination', '0002_destination_accomodation_destination_best_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='destination',
            field=models.ManyToManyField(blank=True, help_text='Destination', null=True, to='destination.destination'),
        ),
    ]
