# Generated by Django 5.2.3 on 2025-07-02 17:10

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Querer name', max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Querer phone number', max_length=128, region=None)),
                ('message', models.TextField(help_text='Querer message', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
            },
        ),
    ]
