# Generated by Django 5.2.3 on 2025-07-02 17:56

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='message',
            field=models.TextField(help_text='Additional message', max_length=240),
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(help_text='Full name', max_length=100),
        ),
        migrations.AlterField(
            model_name='query',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number', max_length=128, region=None),
        ),
    ]
