# Generated by Django 5.2.3 on 2025-07-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='accomodation',
            field=models.CharField(blank=True, help_text='Accomodation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='best_season',
            field=models.CharField(blank=True, help_text='Best Season', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('AUD', 'Aud'), ('NPR', 'Npr'), ('INR', 'Inr')], default='USD', help_text='Currency', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='duration',
            field=models.CharField(blank=True, help_text='Duration', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='feature_image',
            field=models.ImageField(blank=True, help_text='Upload an image file', null=True, upload_to='images/destinations'),
        ),
        migrations.AddField(
            model_name='destination',
            name='gear_equipment',
            field=models.TextField(blank=True, help_text='Gear and Equipment', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='group_size',
            field=models.CharField(blank=True, help_text='Group Size', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='inclusion_exclusions',
            field=models.TextField(blank=True, help_text='Inclusions and Exclusions', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_allowed',
            field=models.BooleanField(default=False, help_text='Is Price Allowed?'),
        ),
        migrations.AddField(
            model_name='destination',
            name='itinerary',
            field=models.TextField(blank=True, help_text='Itinerary', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='max_altitude',
            field=models.CharField(blank=True, help_text='Max Altitude', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='meals',
            field=models.CharField(blank=True, help_text='Meals', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_descrip',
            field=models.CharField(blank=True, help_text='Meta Description', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Meta Keywords', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='nature_of_trip',
            field=models.CharField(blank=True, help_text='Nature of Trip', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='overview',
            field=models.TextField(blank=True, help_text='Overview', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='package',
            field=models.ManyToManyField(to='package.package'),
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='title',
            field=models.CharField(default='', help_text='Destination Title', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='trip_grade',
            field=models.CharField(blank=True, help_text='Trip Grade', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='trip_map',
            field=models.ImageField(blank=True, help_text='Upload an image file', null=True, upload_to='images/trip_map'),
        ),
        migrations.AddField(
            model_name='destination',
            name='trip_map_link',
            field=models.URLField(blank=True, help_text='Trip Map Link', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='trip_pdf',
            field=models.FileField(blank=True, help_text='Upload a pdf file', null=True, upload_to='pdf/trips'),
        ),
        migrations.AddField(
            model_name='destination',
            name='useful_info',
            field=models.TextField(blank=True, help_text='Useful Information', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Departure Start Date')),
                ('end_date', models.DateField(help_text='Departure End Date')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price', max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('AUD', 'Aud'), ('NPR', 'Npr'), ('INR', 'Inr')], default='USD', help_text='Currency', max_length=3, null=True)),
                ('status', models.CharField(choices=[('Guaranteed', 'Gua'), ('Not Guaranteed', 'Notgua')], default='Guaranteed', help_text='Status', max_length=100)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='destination.destination')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image file', upload_to='images/gallery')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='destination.destination')),
            ],
        ),
    ]
